# This was in part taken from: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

image: python:3.9

.default_rules:
  master-version:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+([^-].*)?/'
  manual-version:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-.*/'
      when: manual

.setup_poetry:
  script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry config virtualenvs.create false

.install:
  script:
    - !reference [.setup_poetry, script]
    - poetry install --without=dev

.install_dev:
  script:
    - !reference [.setup_poetry, script]
    - poetry install

.setup_pypi:
  script:
    - poetry config pypi-token.pypi ${PYPI_TOKEN}

.setup_testpypi:
  script:
    - poetry config repositories.testpypi https://test.pypi.org/legacy/
    - poetry config pypi-token.testpypi ${TESTPYPI_TOKEN}

before_script:
  - python --version  # For debugging

flake8 check:
  needs: []
  script:
    - !reference [.install_dev, script]
    - poetry run flake8 "${CI_PROJECT_DIR}" --count --statistics

black check:
  needs: []
  script:
    - !reference [.install_dev, script]
    - poetry run black --check "${CI_PROJECT_DIR}"

isort check:
  needs: []
  script:
    - !reference [.install_dev, script]
    - poetry run isort --check --settings-path pyproject.toml "${CI_PROJECT_DIR}"

publish pypi:
  needs: ["flake8 check", "black check", "isort check"]
  script:
    - !reference [.install, script]
    - !reference [.setup_pypi, script]
    - poetry publish --build
  rules:
    - !reference [.default_rules, master-version]

publish testpypi:
  needs: ["flake8 check", "black check", "isort check"]
  script:
    - !reference [.install, script]
    - !reference [.setup_testpypi, script]
    - poetry publish --build -r testpypi
  rules:
    - !reference [.default_rules, master-version]

publish testpypi manually:
  needs: []
  script:
    - !reference [.install, script]
    - !reference [.setup_testpypi, script]
    - poetry publish --build -r testpypi
  rules:
    - !reference [.default_rules, manual-version]
