image: python:3.9

stages:
  - lint
  - bump
  - release
  - deploy

include:
  - '.gitlab/pipelines/bump-version.yml'
  - '.gitlab/pipelines/setup.yml'
  - '.gitlab/pipelines/lint.yml'
  - '.gitlab/pipelines/deploy.yml'