# This was in part taken from: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

image: python:3.9

before_script:
  - python --version  # For debugging

stages:
  - "Build and test"

    # build executables:
    #   stage: "Build and test"
    #   variables:
    #     SRCDIR: "$CI_PROJECT_DIR"
    #     PLATFORMS: "linux,windows"
    #   image:
    #     name: fydeinc/pyinstaller
    #     entrypoint: [""]
    #   script:
    #     - pwd
    #     - pip install --upgrade pip
    #     - pip install poetry
    #     - poetry config virtualenvs.create false
    #     - poetry export --without-hashes -o requirements.txt
    #     - /entrypoint.sh --onefile --noconsole main.py
    #     - mv "dist/linux/main" "${CI_PROJECT_DIR}/annotation-tool-linux"
    #     - mv "dist/windows/main.exe" "${CI_PROJECT_DIR}/annotation-tool-windows.exe"
    #   artifacts:
    #     paths:
    #       - annotation-tool-linux
    #       - annotation-tool-windows.exe

flake8 linting:
  stage: "Build and test"
  script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install
    - poetry run flake8 "${CI_PROJECT_DIR}"
