image: python:3.9

stages:
  - lint
  - bump
  - deploy

before_script:
  - python --version  # For debugging

include:
  - '.gitlab/pipelines/bump-version.yml'
  - '.gitlab/pipelines/setup.yml'
  - '.gitlab/pipelines/lint.yml'
  - '.gitlab/pipelines/deploy.yml'