fail_fast: true
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: local
    hooks:
      - id: system
        name: Code Style Check (black)
        entry: make test-black
        language: system
        pass_filenames: false
        stages:
          - commit
      - id: system
        name: Code Style Check (flake8)
        entry: make test-flake8
        language: system
        pass_filenames: false
        stages:
          - commit
      - id: system
        name: Code Style Check (isort)
        entry: make test-isort
        language: system
        pass_filenames: false
        stages:
          - commit
